### PR TITLE
Fix for markdown equation formatting

### PR DESCRIPTION
**Pull request by robbotorigami**
I was having similar issues to those reported in https://github.com/quarto-dev/jupyterlab-quarto/issues/7 and https://github.com/quarto-dev/jupyterlab-quarto/issues/3 , and dug in a bit to see what the problem was. I found that the way the MutationObserver architecture was set up for triggering MathJax.typesetPromise did not match the DOM layout I was getting from jupyterlab. I'm not sure why this seems to be different for different users - presumably an underlying jupyterlab reason. I rewrote the architecture so that it should be much less fragile to changes in the document structure, and this seems to resolve the issue.

### CODE REVIEW

**Comment by robbotorigami** [comment]
@dragonstyle or @cscheid Is there any feedback that can be given on this PR? I would really like to use this plugin when editing notebooks for use with quarto, but rendering issues with mathjax is a deal-breaker.

**Comment by dragonstyle** [comment]
Apologies for not getting to this sooner. If I understand the change correctly, it seems like the biggest change is that the whole document is observed (rather than attempting to observe the cells). This definitely seems like it would be more robust, but will mean that we typeset the math each time any part of the document is mutated - does that also seem correct to you? In your observation does this typesetting cause any latency of have observable downsides in normal / large notebooks?

**Comment by robbotorigami** [comment]
@dragonstyle no worries, and thank you for taking a look (and all your other work on this project). 

The whole document is being observed, but it's only looking through the addedNode list for each mutation for the `.quarto-<inline|display>-math` elements. In theory this would mean that only those in a cell getting executed (and thus with a newly added output node) would be provided to Mathjax.typesetPromise. In practice, it seems that there's a number of other events causing mutations: scrolling, selecting cells, etc, but it doesn't seem to be egregious.  It's also worth noting that calling typesetPromise should be fairly low overhead for math that is already typeset (though presumably there is some amount of overhead).

I just made a notebook with a couple hundred equations to try with both versions of this plugin. I think performance is actually slightly better with this change, but they're pretty similar so it could easily be due to something else. Both are much slower than in base jupyterlab, but I imagine that's an unrealistic goal post.

For context, (and hopefully I'm remembering this correctly), I had issues with the existing two-tier mutation observer approach since the element containing `jp-MarkdownCell` was getting recreated each time the cell was executed, and I couldn't find a way to make it work with code cells display markdown output (with IPython.Markdown).

**Comment by dragonstyle** [comment]
Ok, thank you for your diligence. I think that two tier approach was in part my attempt to thread the needle and avoid all those mutations triggering typesetting, but I also recall having issues with recreated cells and sorting out how to observe those with that approach.

**Pull request merged**
